version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci: "
    labels:
      - ":zap: ci/cd"
      - "dependencies"
      - "triage"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: production
      - dependency-type: development
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
    commit-message:
      prefix: "fix: "
    labels:
      - "dependencies"
      - "triage"

  - package-ecosystem: npm
    directory: /test/fixtures/resolution/fake-tree/a
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/resolution/fake-tree/b
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/resolution
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/rollup-v4
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/vite-v5
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/vite-v6
    schedule:
      interval: daily
