version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci: "
    labels:
      - ":zap: ci/cd"
      - "dependencies"
      - "triage"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: production
      - dependency-type: development
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
    commit-message:
      prefix: "fix: "
    labels:
      - "dependencies"
      - "triage"
