# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
enable_free_tier: true
reviews:
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!dist/**"
    - "!.husky/**"
    - "!test/fixtures/**"
